name: Sparrow
main: net.momirealms.sparrow.bukkit.loader.BukkitLoaderPlugin
version: ${project_version}
author: XiaoMoMi
contributors:
  - g2213swo
  - jhqwqmc
softdepend:
  - PlaceholderAPI
api-version: 1.18
folia-supported: true